apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
  namespace: identity
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      name: identity-deployment
      labels:
        app: identity
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: identity-serviceaccount
      containers:
        - name: identity
          image: playeconomy01acr.azurecr.io/play.identity:1.0.11
          env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: ServiceSettings__KeyVaultName
              value: playeconomy-01
            - name: IdentitySettings__PathBase
              value: /identity-svc
            - name: IdentitySettings__CertificateCerFilePath
              value: "/certificates/certificate.crt"
            - name: IdentitySettings__CertificateKeyFilePath
              value: "/certificates/certificate.key"
            - name: IdentityServerSettings__Clients__0__RedirectUris__1
              value: https://playeconomy-01.westus.cloudapp.azure.com/authentication/login-callback
            - name: IdentityServerSettings__Clients__0__PostLogoutRedirectUris__1
              value: https://playeconomy-01.westus.cloudapp.azure.com/authentication/logout-callback
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5002
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5002
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5002
            initialDelaySeconds: 10
          volumeMounts:
            - name: certificate-volume
              mountPath: /certificates
      volumes:
        - name: certificate-volume
          secret:
            secretName: signing-cert
            items:
              - key: tls.key
                path: certificate.key
              - key: tls.crt
                path: certificate.crt
           
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
    - port: 80
      targetPort: 5002
      
---
apiVersion: v1 
kind: ServiceAccount
metadata:
  name: identity-serviceaccount
  annotations:
    azure.workload.identity/client-id: 3871e3f8-5b77-45b9-b3ba-9b43cc38e3a4
  labels:
    azure.workload.identity/use: "true"