microserviceName: "identity"

image: 
  repository: playeconomyapp.azurecr.io/play.identity
  tag : 1.0.23
  
envVariables:
  IdentitySettings__PathBase: /identity-svc
  IdentitySettings__CertificateCerFilePath: "/certificates/certificate.crt"
  IdentitySettings__CertificateKeyFilePath: "/certificates/certificate.key"
  IdentityServerSettings__Clients__1__RedirectUris__0: https://playeconomyapp.westus.cloudapp.azure.com/authentication/login-callback
  IdentityServerSettings__Clients__1__PostLogoutRedirectUris__0: https://playeconomyapp.westus.cloudapp.azure.com/authentication/logout-callback
    
resources:
  limits:
    memory: "256Mi"
    cpu: "150m"
    
container:
  port: 5002
  volumeMounts:
    - name: certificate-volume
      mountPath: /certificates

volumes:
  - name: certificate-volume
    secret:
      secretName: signing-cert
      items:
        - key: tls.key
          path: certificate.key
        - key: tls.crt
          path: certificate.crt

certificate:
  secretName: signing-cert
  hostname: "playeconomyapp.westus.cloudapp.azure.com"
    
identityClientId: 304c2a78-8559-49b7-914d-5a5d6ef3c998
    